### ISSUE TITLE
Default YAML corpus list is not in the right location

### ISSUE THREAD

**Issue by dav009** [DH-Box/corpus-downloader#11]
it seems when cloning, and running `pip3 install .` 
the resource: https://github.com/JonathanReeve/corpus-list/ does not get cloned/dont get added to the pypy package.

**Comment by JonathanReeve** [comment]
Thanks for the bug report! Indeed, this issue has been a major pain. It has something to do with the way setuptools packages data files. I reconfigured it now, though, so it should be working. I've also updated the install instructions with an easier installation method, in addition to the one that git clones from this repo. Let me know if it works for you. I'll close this for the moment, but feel free to reopen if you're still having issues.

**Comment by dav009** [comment]
@JonathanReeve actually my last PR addresses some of the issues by providing an update command, and download the list the first time the program is ran.

problem with shipping the list with the package is that you are tighting the version of `corpus-downloaded` to the content of the list

**Comment by JonathanReeve** [comment]
Thanks for that! It's awesome. I'm working on merging it at the moment. I ended up just taking out the config file, since I was having difficulty packaging it and shipping it via PyPi, so I'm working on a hybrid approach that uses your PR and some fancy resource lookup stuff from setuptools for managing the corpus list. I'll put all this on the `develop` branch for the moment, and then merge it into master soon.

**Comment by dav009** [comment]
sounds great.

any plan for unit-tests ? I was a bit afraid of breaking other things.
If you add an issue, and agree on some basic ones, Im happy to give a hand.

**Comment by JonathanReeve** [comment]
Totally. I just added #16 for that. I don't have too much experience writing unit tests in Python, so feel free to take a crack at it. That's a little low on my priority list at the moment, but I can definitely see the appeal. I'd especially like to have a Travis CI workflow set up at some point, too. I'm not quite sure what that'll look like yet, but that one's at #17.
